[build]
target = "index.html"
dist = "./dist"
public_url = "./dist/"

[[proxy]]
backend = "http://127.0.0.1:8080"

[[hooks]]
stage = "build"
command = "cmd"
command_arguments = ["/C", "npx tailwindcss -i ./styles/input.css -o ./styles/output.css"]